# Generated by Django 6.0.2 on 2026-02-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['fname'],
            },
        ),
    ]
